name: Publish API docs

# Run on every push, but only publish if it is to the main branch.

on: [push]

jobs:
  build:
    name: Check or publish API docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get install -y build-essential ninja-build doxygen
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install meson
      - name: Build docs
        run: |
          meson setup builddir
          cd builddir
          ninja doc/doxygen
      - name: Publish docs (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builddir/doc/doxygen/html
