# This file is part of RichErrors.
# Copyright 2019-2022 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: BSD-2-Clause

name: Check build

# Run the build to make sure it works (we do not currently publish the
# artifacts, because being a static library, it almost always has to be built in
# the user's environment anyway).

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - os: ubuntu
            runner: ubuntu-latest
          - os: macos
            runner: macos-latest
          - os: windows
            runner: windows-latest

    name: ${{ matrix.runner }} build check

    runs-on: ${{ matrix.runner }}

    steps:

      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install tools (Ubuntu)
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get install -y build-essential ninja-build doxygen
          # Install Meson via pip rather than apt to get latest version
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install meson

      - name: Install tools (macOS)
        if: matrix.os == 'macos'
        run: |
          brew install meson ninja doxygen

      - name: Install tools (Windows)
        if: matrix.os == 'windows'
        run: |
          choco install -y ninja doxygen.install
          python3 -m pip install --upgrade pip
          python3 -m pip install meson

      - name: Build (Unix)
        if: matrix.os != 'windows'
        run: |
          mkdir stage
          meson setup --prefix=$(pwd)/stage builddir
          cd builddir
          ninja test
          ninja install

      - name: Build (Windows)
        if: matrix.os == 'windows'
        run: |
          mkdir C:/stage
          meson setup --prefix=C:/stage builddir
          cd builddir
          ninja test
          ninja install
